version: '3'

services:
  postgres:
    image: bitnami/postgresql
    container_name: ignite-gym
    environment:
      - POSTGRESQL_USERNAME=aszurar
      - POSTGRESQL_PASSWORD=aszurar.nichi
      - POSTGRESQL_DATABASE=ignitegym
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: